### ISSUE TITLE
npm run preview generate the following error

### ISSUE THREAD

**Issue by xfinitysoft** [m-Ryan/easy-email#4] opened 2021-07-31 00:44 UTC
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @/hooks/useFocusIdx (imported by  /Email-Builder/example/pages/Editor/components/CustomBlocks/ProductRecommendation/Panel/index.tsx)

Are they installed?
    at optimizeDeps (\Email-Builder\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73153:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOptimize (Email-Builder\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73827:48)
    at async Server.httpServer.listen (Email-Builder\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73843:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easy-email-editor@1.1.4 preview: `npm run lib && vite --config vite.preview.config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easy-email-editor@1.1.4 preview script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by m-Ryan** [comment] 2021-08-01 04:13
![image](https://user-images.githubusercontent.com/20615214/127758929-c918b435-c503-4cff-a8a7-f74f3556c4a0.png)

The cause of the bug is the wrong import, fixed now.

**Closed** 2021-08-01 04:16 UTC
